stages:
  - Test
  - Build

Test:
  stage: Test
  image: golang:1.23
  only:
    - main
  before_script:
    - go env -w GOPROXY=https://goproxy.cn,direct
  script:
    - go test ./... -v

BuildBinary:
  stage: Build
  image: golang:1.23
  only:
    - main
  needs:
    - job: Test
  before_script:
    - go env -w GOPROXY=https://goproxy.cn,direct
  script:
    - make build
  artifacts:
    expire_in: 1 day
    paths:
      - ./bin/neurouter

BuildImage:
  stage: Build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  only:
    - main
  needs:
    - job: BuildBinary
  script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "ctrysbita" "${IMAGE_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "ctrysbita/neurouter:${CI_PIPELINE_IID}"
