// Copyright 2024 Neurouter Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: conf/upstream.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Modality defines the types of input/output the model can handle.
type Modality int32

const (
	Modality_MODALITY_UNSPECIFIED Modality = 0
	Modality_MODALITY_TEXT        Modality = 1
	Modality_MODALITY_IMAGE       Modality = 2
	Modality_MODALITY_AUDIO       Modality = 3
	Modality_MODALITY_VIDEO       Modality = 4
)

// Enum value maps for Modality.
var (
	Modality_name = map[int32]string{
		0: "MODALITY_UNSPECIFIED",
		1: "MODALITY_TEXT",
		2: "MODALITY_IMAGE",
		3: "MODALITY_AUDIO",
		4: "MODALITY_VIDEO",
	}
	Modality_value = map[string]int32{
		"MODALITY_UNSPECIFIED": 0,
		"MODALITY_TEXT":        1,
		"MODALITY_IMAGE":       2,
		"MODALITY_AUDIO":       3,
		"MODALITY_VIDEO":       4,
	}
)

func (x Modality) Enum() *Modality {
	p := new(Modality)
	*p = x
	return p
}

func (x Modality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modality) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_upstream_proto_enumTypes[0].Descriptor()
}

func (Modality) Type() protoreflect.EnumType {
	return &file_conf_upstream_proto_enumTypes[0]
}

func (x Modality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modality.Descriptor instead.
func (Modality) EnumDescriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{0}
}

// Capability defines what the model can do.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED Capability = 0
	Capability_CAPABILITY_CHAT        Capability = 1
	Capability_CAPABILITY_COMPLETION  Capability = 2
	Capability_CAPABILITY_EMBEDDING   Capability = 3
	Capability_CAPABILITY_TOOL_USE    Capability = 4
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_CHAT",
		2: "CAPABILITY_COMPLETION",
		3: "CAPABILITY_EMBEDDING",
		4: "CAPABILITY_TOOL_USE",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED": 0,
		"CAPABILITY_CHAT":        1,
		"CAPABILITY_COMPLETION":  2,
		"CAPABILITY_EMBEDDING":   3,
		"CAPABILITY_TOOL_USE":    4,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_conf_upstream_proto_enumTypes[1].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_conf_upstream_proto_enumTypes[1]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{1}
}

type Upstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*UpstreamConfig      `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_conf_upstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{0}
}

func (x *Upstream) GetConfigs() []*UpstreamConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type UpstreamConfig struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Models []*Model               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*UpstreamConfig_Neurouter
	//	*UpstreamConfig_OpenAi
	//	*UpstreamConfig_Google
	//	*UpstreamConfig_Anthropic
	//	*UpstreamConfig_DeepSeek
	Config        isUpstreamConfig_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamConfig) Reset() {
	*x = UpstreamConfig{}
	mi := &file_conf_upstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamConfig) ProtoMessage() {}

func (x *UpstreamConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamConfig.ProtoReflect.Descriptor instead.
func (*UpstreamConfig) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{1}
}

func (x *UpstreamConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpstreamConfig) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *UpstreamConfig) GetConfig() isUpstreamConfig_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpstreamConfig) GetNeurouter() *NeurouterConfig {
	if x != nil {
		if x, ok := x.Config.(*UpstreamConfig_Neurouter); ok {
			return x.Neurouter
		}
	}
	return nil
}

func (x *UpstreamConfig) GetOpenAi() *OpenAIConfig {
	if x != nil {
		if x, ok := x.Config.(*UpstreamConfig_OpenAi); ok {
			return x.OpenAi
		}
	}
	return nil
}

func (x *UpstreamConfig) GetGoogle() *GoogleConfig {
	if x != nil {
		if x, ok := x.Config.(*UpstreamConfig_Google); ok {
			return x.Google
		}
	}
	return nil
}

func (x *UpstreamConfig) GetAnthropic() *AnthropicConfig {
	if x != nil {
		if x, ok := x.Config.(*UpstreamConfig_Anthropic); ok {
			return x.Anthropic
		}
	}
	return nil
}

func (x *UpstreamConfig) GetDeepSeek() *DeepSeekConfig {
	if x != nil {
		if x, ok := x.Config.(*UpstreamConfig_DeepSeek); ok {
			return x.DeepSeek
		}
	}
	return nil
}

type isUpstreamConfig_Config interface {
	isUpstreamConfig_Config()
}

type UpstreamConfig_Neurouter struct {
	Neurouter *NeurouterConfig `protobuf:"bytes,100,opt,name=neurouter,proto3,oneof"`
}

type UpstreamConfig_OpenAi struct {
	OpenAi *OpenAIConfig `protobuf:"bytes,101,opt,name=open_ai,json=openAi,proto3,oneof"`
}

type UpstreamConfig_Google struct {
	Google *GoogleConfig `protobuf:"bytes,102,opt,name=google,proto3,oneof"`
}

type UpstreamConfig_Anthropic struct {
	Anthropic *AnthropicConfig `protobuf:"bytes,103,opt,name=anthropic,proto3,oneof"`
}

type UpstreamConfig_DeepSeek struct {
	DeepSeek *DeepSeekConfig `protobuf:"bytes,104,opt,name=deep_seek,json=deepSeek,proto3,oneof"`
}

func (*UpstreamConfig_Neurouter) isUpstreamConfig_Config() {}

func (*UpstreamConfig_OpenAi) isUpstreamConfig_Config() {}

func (*UpstreamConfig_Google) isUpstreamConfig_Config() {}

func (*UpstreamConfig_Anthropic) isUpstreamConfig_Config() {}

func (*UpstreamConfig_DeepSeek) isUpstreamConfig_Config() {}

type Model struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the model.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The unique identifier of the model in the upstream.
	UpstreamId string `protobuf:"bytes,2,opt,name=upstream_id,json=upstreamId,proto3" json:"upstream_id,omitempty"`
	// The display name of the model.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The entity that owns the model.
	From string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	// The model service provider.
	Provider string `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	// The modalities supported by the model.
	Modalities []Modality `protobuf:"varint,6,rep,packed,name=modalities,proto3,enum=neurouter.config.v1.Modality" json:"modalities,omitempty"`
	// The capabilities of the model.
	Capabilities  []Capability `protobuf:"varint,7,rep,packed,name=capabilities,proto3,enum=neurouter.config.v1.Capability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_conf_upstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetUpstreamId() string {
	if x != nil {
		return x.UpstreamId
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Model) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Model) GetModalities() []Modality {
	if x != nil {
		return x.Modalities
	}
	return nil
}

func (x *Model) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type NeurouterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeurouterConfig) Reset() {
	*x = NeurouterConfig{}
	mi := &file_conf_upstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeurouterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeurouterConfig) ProtoMessage() {}

func (x *NeurouterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeurouterConfig.ProtoReflect.Descriptor instead.
func (*NeurouterConfig) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{3}
}

func (x *NeurouterConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

type OpenAIConfig struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	ApiKey                          string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl                         string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	PreferStringContentForSystem    bool                   `protobuf:"varint,3,opt,name=prefer_string_content_for_system,json=preferStringContentForSystem,proto3" json:"prefer_string_content_for_system,omitempty"`
	PreferStringContentForUser      bool                   `protobuf:"varint,4,opt,name=prefer_string_content_for_user,json=preferStringContentForUser,proto3" json:"prefer_string_content_for_user,omitempty"`
	PreferStringContentForAssistant bool                   `protobuf:"varint,5,opt,name=prefer_string_content_for_assistant,json=preferStringContentForAssistant,proto3" json:"prefer_string_content_for_assistant,omitempty"`
	PreferStringContentForTool      bool                   `protobuf:"varint,6,opt,name=prefer_string_content_for_tool,json=preferStringContentForTool,proto3" json:"prefer_string_content_for_tool,omitempty"`
	PreferSinglePartContent         bool                   `protobuf:"varint,7,opt,name=prefer_single_part_content,json=preferSinglePartContent,proto3" json:"prefer_single_part_content,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *OpenAIConfig) Reset() {
	*x = OpenAIConfig{}
	mi := &file_conf_upstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIConfig) ProtoMessage() {}

func (x *OpenAIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIConfig.ProtoReflect.Descriptor instead.
func (*OpenAIConfig) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{4}
}

func (x *OpenAIConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *OpenAIConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *OpenAIConfig) GetPreferStringContentForSystem() bool {
	if x != nil {
		return x.PreferStringContentForSystem
	}
	return false
}

func (x *OpenAIConfig) GetPreferStringContentForUser() bool {
	if x != nil {
		return x.PreferStringContentForUser
	}
	return false
}

func (x *OpenAIConfig) GetPreferStringContentForAssistant() bool {
	if x != nil {
		return x.PreferStringContentForAssistant
	}
	return false
}

func (x *OpenAIConfig) GetPreferStringContentForTool() bool {
	if x != nil {
		return x.PreferStringContentForTool
	}
	return false
}

func (x *OpenAIConfig) GetPreferSinglePartContent() bool {
	if x != nil {
		return x.PreferSinglePartContent
	}
	return false
}

type GoogleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleConfig) Reset() {
	*x = GoogleConfig{}
	mi := &file_conf_upstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleConfig) ProtoMessage() {}

func (x *GoogleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleConfig.ProtoReflect.Descriptor instead.
func (*GoogleConfig) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{5}
}

func (x *GoogleConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type AnthropicConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ApiKey  string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// Whether to put the system prompt into messages (as user message)
	SystemAsUser  bool `protobuf:"varint,3,opt,name=system_as_user,json=systemAsUser,proto3" json:"system_as_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicConfig) Reset() {
	*x = AnthropicConfig{}
	mi := &file_conf_upstream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicConfig) ProtoMessage() {}

func (x *AnthropicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicConfig.ProtoReflect.Descriptor instead.
func (*AnthropicConfig) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{6}
}

func (x *AnthropicConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AnthropicConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AnthropicConfig) GetSystemAsUser() bool {
	if x != nil {
		return x.SystemAsUser
	}
	return false
}

type DeepSeekConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepSeekConfig) Reset() {
	*x = DeepSeekConfig{}
	mi := &file_conf_upstream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepSeekConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepSeekConfig) ProtoMessage() {}

func (x *DeepSeekConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_upstream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepSeekConfig.ProtoReflect.Descriptor instead.
func (*DeepSeekConfig) Descriptor() ([]byte, []int) {
	return file_conf_upstream_proto_rawDescGZIP(), []int{7}
}

func (x *DeepSeekConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeepSeekConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

var File_conf_upstream_proto protoreflect.FileDescriptor

const file_conf_upstream_proto_rawDesc = "" +
	"\n" +
	"\x13conf/upstream.proto\x12\x13neurouter.config.v1\"I\n" +
	"\bUpstream\x12=\n" +
	"\aconfigs\x18\x01 \x03(\v2#.neurouter.config.v1.UpstreamConfigR\aconfigs\"\xad\x03\n" +
	"\x0eUpstreamConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\x06models\x18\x02 \x03(\v2\x1a.neurouter.config.v1.ModelR\x06models\x12D\n" +
	"\tneurouter\x18d \x01(\v2$.neurouter.config.v1.NeurouterConfigH\x00R\tneurouter\x12<\n" +
	"\aopen_ai\x18e \x01(\v2!.neurouter.config.v1.OpenAIConfigH\x00R\x06openAi\x12;\n" +
	"\x06google\x18f \x01(\v2!.neurouter.config.v1.GoogleConfigH\x00R\x06google\x12D\n" +
	"\tanthropic\x18g \x01(\v2$.neurouter.config.v1.AnthropicConfigH\x00R\tanthropic\x12B\n" +
	"\tdeep_seek\x18h \x01(\v2#.neurouter.config.v1.DeepSeekConfigH\x00R\bdeepSeekB\b\n" +
	"\x06config\"\x80\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vupstream_id\x18\x02 \x01(\tR\n" +
	"upstreamId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12=\n" +
	"\n" +
	"modalities\x18\x06 \x03(\x0e2\x1d.neurouter.config.v1.ModalityR\n" +
	"modalities\x12C\n" +
	"\fcapabilities\x18\a \x03(\x0e2\x1f.neurouter.config.v1.CapabilityR\fcapabilities\"-\n" +
	"\x0fNeurouterConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\"\x9d\x03\n" +
	"\fOpenAIConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12F\n" +
	" prefer_string_content_for_system\x18\x03 \x01(\bR\x1cpreferStringContentForSystem\x12B\n" +
	"\x1eprefer_string_content_for_user\x18\x04 \x01(\bR\x1apreferStringContentForUser\x12L\n" +
	"#prefer_string_content_for_assistant\x18\x05 \x01(\bR\x1fpreferStringContentForAssistant\x12B\n" +
	"\x1eprefer_string_content_for_tool\x18\x06 \x01(\bR\x1apreferStringContentForTool\x12;\n" +
	"\x1aprefer_single_part_content\x18\a \x01(\bR\x17preferSinglePartContent\"'\n" +
	"\fGoogleConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"k\n" +
	"\x0fAnthropicConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12$\n" +
	"\x0esystem_as_user\x18\x03 \x01(\bR\fsystemAsUser\"D\n" +
	"\x0eDeepSeekConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl*s\n" +
	"\bModality\x12\x18\n" +
	"\x14MODALITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMODALITY_TEXT\x10\x01\x12\x12\n" +
	"\x0eMODALITY_IMAGE\x10\x02\x12\x12\n" +
	"\x0eMODALITY_AUDIO\x10\x03\x12\x12\n" +
	"\x0eMODALITY_VIDEO\x10\x04*\x8b\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCAPABILITY_CHAT\x10\x01\x12\x19\n" +
	"\x15CAPABILITY_COMPLETION\x10\x02\x12\x18\n" +
	"\x14CAPABILITY_EMBEDDING\x10\x03\x12\x17\n" +
	"\x13CAPABILITY_TOOL_USE\x10\x04B2Z0github.com/neuraxes/neurouter/internal/conf;confb\x06proto3"

var (
	file_conf_upstream_proto_rawDescOnce sync.Once
	file_conf_upstream_proto_rawDescData []byte
)

func file_conf_upstream_proto_rawDescGZIP() []byte {
	file_conf_upstream_proto_rawDescOnce.Do(func() {
		file_conf_upstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_upstream_proto_rawDesc), len(file_conf_upstream_proto_rawDesc)))
	})
	return file_conf_upstream_proto_rawDescData
}

var file_conf_upstream_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_conf_upstream_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_conf_upstream_proto_goTypes = []any{
	(Modality)(0),           // 0: neurouter.config.v1.Modality
	(Capability)(0),         // 1: neurouter.config.v1.Capability
	(*Upstream)(nil),        // 2: neurouter.config.v1.Upstream
	(*UpstreamConfig)(nil),  // 3: neurouter.config.v1.UpstreamConfig
	(*Model)(nil),           // 4: neurouter.config.v1.Model
	(*NeurouterConfig)(nil), // 5: neurouter.config.v1.NeurouterConfig
	(*OpenAIConfig)(nil),    // 6: neurouter.config.v1.OpenAIConfig
	(*GoogleConfig)(nil),    // 7: neurouter.config.v1.GoogleConfig
	(*AnthropicConfig)(nil), // 8: neurouter.config.v1.AnthropicConfig
	(*DeepSeekConfig)(nil),  // 9: neurouter.config.v1.DeepSeekConfig
}
var file_conf_upstream_proto_depIdxs = []int32{
	3, // 0: neurouter.config.v1.Upstream.configs:type_name -> neurouter.config.v1.UpstreamConfig
	4, // 1: neurouter.config.v1.UpstreamConfig.models:type_name -> neurouter.config.v1.Model
	5, // 2: neurouter.config.v1.UpstreamConfig.neurouter:type_name -> neurouter.config.v1.NeurouterConfig
	6, // 3: neurouter.config.v1.UpstreamConfig.open_ai:type_name -> neurouter.config.v1.OpenAIConfig
	7, // 4: neurouter.config.v1.UpstreamConfig.google:type_name -> neurouter.config.v1.GoogleConfig
	8, // 5: neurouter.config.v1.UpstreamConfig.anthropic:type_name -> neurouter.config.v1.AnthropicConfig
	9, // 6: neurouter.config.v1.UpstreamConfig.deep_seek:type_name -> neurouter.config.v1.DeepSeekConfig
	0, // 7: neurouter.config.v1.Model.modalities:type_name -> neurouter.config.v1.Modality
	1, // 8: neurouter.config.v1.Model.capabilities:type_name -> neurouter.config.v1.Capability
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_conf_upstream_proto_init() }
func file_conf_upstream_proto_init() {
	if File_conf_upstream_proto != nil {
		return
	}
	file_conf_upstream_proto_msgTypes[1].OneofWrappers = []any{
		(*UpstreamConfig_Neurouter)(nil),
		(*UpstreamConfig_OpenAi)(nil),
		(*UpstreamConfig_Google)(nil),
		(*UpstreamConfig_Anthropic)(nil),
		(*UpstreamConfig_DeepSeek)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_upstream_proto_rawDesc), len(file_conf_upstream_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_upstream_proto_goTypes,
		DependencyIndexes: file_conf_upstream_proto_depIdxs,
		EnumInfos:         file_conf_upstream_proto_enumTypes,
		MessageInfos:      file_conf_upstream_proto_msgTypes,
	}.Build()
	File_conf_upstream_proto = out.File
	file_conf_upstream_proto_goTypes = nil
	file_conf_upstream_proto_depIdxs = nil
}
