// Copyright 2024 Neurouter Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: neurouter/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReasoningEffort int32

const (
	ReasoningEffort_REASONING_EFFORT_UNSPECIFIED ReasoningEffort = 0
	ReasoningEffort_REASONING_EFFORT_NONE        ReasoningEffort = 1
	ReasoningEffort_REASONING_EFFORT_MINIMAL     ReasoningEffort = 2
	ReasoningEffort_REASONING_EFFORT_LOW         ReasoningEffort = 3
	ReasoningEffort_REASONING_EFFORT_MEDIUM      ReasoningEffort = 4
	ReasoningEffort_REASONING_EFFORT_HIGH        ReasoningEffort = 5
	ReasoningEffort_REASONING_EFFORT_EXTRA_HIGH  ReasoningEffort = 6
	ReasoningEffort_REASONING_EFFORT_MAX         ReasoningEffort = 7
)

// Enum value maps for ReasoningEffort.
var (
	ReasoningEffort_name = map[int32]string{
		0: "REASONING_EFFORT_UNSPECIFIED",
		1: "REASONING_EFFORT_NONE",
		2: "REASONING_EFFORT_MINIMAL",
		3: "REASONING_EFFORT_LOW",
		4: "REASONING_EFFORT_MEDIUM",
		5: "REASONING_EFFORT_HIGH",
		6: "REASONING_EFFORT_EXTRA_HIGH",
		7: "REASONING_EFFORT_MAX",
	}
	ReasoningEffort_value = map[string]int32{
		"REASONING_EFFORT_UNSPECIFIED": 0,
		"REASONING_EFFORT_NONE":        1,
		"REASONING_EFFORT_MINIMAL":     2,
		"REASONING_EFFORT_LOW":         3,
		"REASONING_EFFORT_MEDIUM":      4,
		"REASONING_EFFORT_HIGH":        5,
		"REASONING_EFFORT_EXTRA_HIGH":  6,
		"REASONING_EFFORT_MAX":         7,
	}
)

func (x ReasoningEffort) Enum() *ReasoningEffort {
	p := new(ReasoningEffort)
	*p = x
	return p
}

func (x ReasoningEffort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasoningEffort) Descriptor() protoreflect.EnumDescriptor {
	return file_neurouter_v1_common_proto_enumTypes[0].Descriptor()
}

func (ReasoningEffort) Type() protoreflect.EnumType {
	return &file_neurouter_v1_common_proto_enumTypes[0]
}

func (x ReasoningEffort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasoningEffort.Descriptor instead.
func (ReasoningEffort) EnumDescriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{0}
}

// Modality defines the types of input/output the model can handle.
type Modality int32

const (
	Modality_MODALITY_UNSPECIFIED Modality = 0
	Modality_MODALITY_TEXT        Modality = 1
	Modality_MODALITY_IMAGE       Modality = 2
	Modality_MODALITY_AUDIO       Modality = 3
	Modality_MODALITY_VIDEO       Modality = 4
)

// Enum value maps for Modality.
var (
	Modality_name = map[int32]string{
		0: "MODALITY_UNSPECIFIED",
		1: "MODALITY_TEXT",
		2: "MODALITY_IMAGE",
		3: "MODALITY_AUDIO",
		4: "MODALITY_VIDEO",
	}
	Modality_value = map[string]int32{
		"MODALITY_UNSPECIFIED": 0,
		"MODALITY_TEXT":        1,
		"MODALITY_IMAGE":       2,
		"MODALITY_AUDIO":       3,
		"MODALITY_VIDEO":       4,
	}
)

func (x Modality) Enum() *Modality {
	p := new(Modality)
	*p = x
	return p
}

func (x Modality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modality) Descriptor() protoreflect.EnumDescriptor {
	return file_neurouter_v1_common_proto_enumTypes[1].Descriptor()
}

func (Modality) Type() protoreflect.EnumType {
	return &file_neurouter_v1_common_proto_enumTypes[1]
}

func (x Modality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modality.Descriptor instead.
func (Modality) EnumDescriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{1}
}

// Capability defines what the model can do.
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED Capability = 0
	Capability_CAPABILITY_CHAT        Capability = 1
	Capability_CAPABILITY_COMPLETION  Capability = 2
	Capability_CAPABILITY_EMBEDDING   Capability = 3
	Capability_CAPABILITY_TOOL_USE    Capability = 4
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_CHAT",
		2: "CAPABILITY_COMPLETION",
		3: "CAPABILITY_EMBEDDING",
		4: "CAPABILITY_TOOL_USE",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED": 0,
		"CAPABILITY_CHAT":        1,
		"CAPABILITY_COMPLETION":  2,
		"CAPABILITY_EMBEDDING":   3,
		"CAPABILITY_TOOL_USE":    4,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_neurouter_v1_common_proto_enumTypes[2].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_neurouter_v1_common_proto_enumTypes[2]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{2}
}

type ReasoningConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The effort level for reasoning.
	Effort ReasoningEffort `protobuf:"varint,1,opt,name=effort,proto3,enum=neurouter.v1.ReasoningEffort" json:"effort,omitempty"`
	// The token budget for reasoning.
	TokenBudget   uint32 `protobuf:"varint,2,opt,name=token_budget,json=tokenBudget,proto3" json:"token_budget,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningConfig) Reset() {
	*x = ReasoningConfig{}
	mi := &file_neurouter_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningConfig) ProtoMessage() {}

func (x *ReasoningConfig) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningConfig.ProtoReflect.Descriptor instead.
func (*ReasoningConfig) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ReasoningConfig) GetEffort() ReasoningEffort {
	if x != nil {
		return x.Effort
	}
	return ReasoningEffort_REASONING_EFFORT_UNSPECIFIED
}

func (x *ReasoningConfig) GetTokenBudget() uint32 {
	if x != nil {
		return x.TokenBudget
	}
	return 0
}

type GenerationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The maximum number of tokens that can be generated.
	MaxTokens *int64 `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3,oneof" json:"max_tokens,omitempty"`
	// The temperature sampling. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
	Temperature *float32 `protobuf:"fixed32,2,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	// The nucleus sampling, where the model considers the results of the tokens with top_p probability mass.
	TopP *float32 `protobuf:"fixed32,3,opt,name=top_p,json=topP,proto3,oneof" json:"top_p,omitempty"`
	// The top_k sampling, where the model considers the results of the top_k most probable tokens.
	TopK *int64 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3,oneof" json:"top_k,omitempty"`
	// Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
	FrequencyPenalty *float32 `protobuf:"fixed32,5,opt,name=frequency_penalty,json=frequencyPenalty,proto3,oneof" json:"frequency_penalty,omitempty"`
	// Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
	PresencePenalty *float32 `protobuf:"fixed32,6,opt,name=presence_penalty,json=presencePenalty,proto3,oneof" json:"presence_penalty,omitempty"`
	// Configuration for reasoning.
	ReasoningConfig *ReasoningConfig `protobuf:"bytes,7,opt,name=reasoning_config,json=reasoningConfig,proto3,oneof" json:"reasoning_config,omitempty"`
	// The sequences where the model will stop generating further tokens.
	StopSequences []string `protobuf:"bytes,8,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	// Types that are valid to be assigned to Template:
	//
	//	*GenerationConfig_PresetTemplate
	Template isGenerationConfig_Template `protobuf_oneof:"template"`
	// Types that are valid to be assigned to Grammar:
	//
	//	*GenerationConfig_PresetGrammar
	//	*GenerationConfig_GbnfGrammar
	//	*GenerationConfig_Schema
	Grammar       isGenerationConfig_Grammar `protobuf_oneof:"grammar"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationConfig) Reset() {
	*x = GenerationConfig{}
	mi := &file_neurouter_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationConfig) ProtoMessage() {}

func (x *GenerationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationConfig.ProtoReflect.Descriptor instead.
func (*GenerationConfig) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *GenerationConfig) GetMaxTokens() int64 {
	if x != nil && x.MaxTokens != nil {
		return *x.MaxTokens
	}
	return 0
}

func (x *GenerationConfig) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *GenerationConfig) GetTopP() float32 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *GenerationConfig) GetTopK() int64 {
	if x != nil && x.TopK != nil {
		return *x.TopK
	}
	return 0
}

func (x *GenerationConfig) GetFrequencyPenalty() float32 {
	if x != nil && x.FrequencyPenalty != nil {
		return *x.FrequencyPenalty
	}
	return 0
}

func (x *GenerationConfig) GetPresencePenalty() float32 {
	if x != nil && x.PresencePenalty != nil {
		return *x.PresencePenalty
	}
	return 0
}

func (x *GenerationConfig) GetReasoningConfig() *ReasoningConfig {
	if x != nil {
		return x.ReasoningConfig
	}
	return nil
}

func (x *GenerationConfig) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

func (x *GenerationConfig) GetTemplate() isGenerationConfig_Template {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *GenerationConfig) GetPresetTemplate() string {
	if x != nil {
		if x, ok := x.Template.(*GenerationConfig_PresetTemplate); ok {
			return x.PresetTemplate
		}
	}
	return ""
}

func (x *GenerationConfig) GetGrammar() isGenerationConfig_Grammar {
	if x != nil {
		return x.Grammar
	}
	return nil
}

func (x *GenerationConfig) GetPresetGrammar() string {
	if x != nil {
		if x, ok := x.Grammar.(*GenerationConfig_PresetGrammar); ok {
			return x.PresetGrammar
		}
	}
	return ""
}

func (x *GenerationConfig) GetGbnfGrammar() string {
	if x != nil {
		if x, ok := x.Grammar.(*GenerationConfig_GbnfGrammar); ok {
			return x.GbnfGrammar
		}
	}
	return ""
}

func (x *GenerationConfig) GetSchema() *structpb.Struct {
	if x != nil {
		if x, ok := x.Grammar.(*GenerationConfig_Schema); ok {
			return x.Schema
		}
	}
	return nil
}

type isGenerationConfig_Template interface {
	isGenerationConfig_Template()
}

type GenerationConfig_PresetTemplate struct {
	PresetTemplate string `protobuf:"bytes,50,opt,name=preset_template,json=presetTemplate,proto3,oneof"`
}

func (*GenerationConfig_PresetTemplate) isGenerationConfig_Template() {}

type isGenerationConfig_Grammar interface {
	isGenerationConfig_Grammar()
}

type GenerationConfig_PresetGrammar struct {
	// Preset grammars, e.g. "text", "json_object", etc.
	PresetGrammar string `protobuf:"bytes,60,opt,name=preset_grammar,json=presetGrammar,proto3,oneof"`
}

type GenerationConfig_GbnfGrammar struct {
	// The GGML BNF grammar definition.
	GbnfGrammar string `protobuf:"bytes,61,opt,name=gbnf_grammar,json=gbnfGrammar,proto3,oneof"`
}

type GenerationConfig_Schema struct {
	// The schema definition.
	Schema *structpb.Struct `protobuf:"bytes,62,opt,name=schema,proto3,oneof"`
}

func (*GenerationConfig_PresetGrammar) isGenerationConfig_Grammar() {}

func (*GenerationConfig_GbnfGrammar) isGenerationConfig_Grammar() {}

func (*GenerationConfig_Schema) isGenerationConfig_Grammar() {}

// Statistics contains token usage information for a model invocation.
type Statistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usage         *Statistics_Usage      `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statistics) Reset() {
	*x = Statistics{}
	mi := &file_neurouter_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics) ProtoMessage() {}

func (x *Statistics) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics.ProtoReflect.Descriptor instead.
func (*Statistics) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *Statistics) GetUsage() *Statistics_Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

type Tool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Tool:
	//
	//	*Tool_Function_
	Tool          isTool_Tool `protobuf_oneof:"tool"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_neurouter_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Tool) GetTool() isTool_Tool {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *Tool) GetFunction() *Tool_Function {
	if x != nil {
		if x, ok := x.Tool.(*Tool_Function_); ok {
			return x.Function
		}
	}
	return nil
}

type isTool_Tool interface {
	isTool_Tool()
}

type Tool_Function_ struct {
	Function *Tool_Function `protobuf:"bytes,1,opt,name=function,proto3,oneof"`
}

func (*Tool_Function_) isTool_Tool() {}

type Statistics_Usage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of input tokens, including cached tokens.
	InputTokens uint32 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	// Number of output tokens generated by the model.
	OutputTokens uint32 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	// Number of input tokens served from prompt cache (subset of input_tokens).
	CachedInputTokens uint32 `protobuf:"varint,3,opt,name=cached_input_tokens,json=cachedInputTokens,proto3" json:"cached_input_tokens,omitempty"`
	// Number of reasoning tokens consumed (subset of output_tokens for reasoning models).
	ReasoningTokens uint32 `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Statistics_Usage) Reset() {
	*x = Statistics_Usage{}
	mi := &file_neurouter_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statistics_Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statistics_Usage) ProtoMessage() {}

func (x *Statistics_Usage) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statistics_Usage.ProtoReflect.Descriptor instead.
func (*Statistics_Usage) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Statistics_Usage) GetInputTokens() uint32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Statistics_Usage) GetOutputTokens() uint32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Statistics_Usage) GetCachedInputTokens() uint32 {
	if x != nil {
		return x.CachedInputTokens
	}
	return 0
}

func (x *Statistics_Usage) GetReasoningTokens() uint32 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

type Tool_Function struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool_Function) Reset() {
	*x = Tool_Function{}
	mi := &file_neurouter_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool_Function) ProtoMessage() {}

func (x *Tool_Function) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool_Function.ProtoReflect.Descriptor instead.
func (*Tool_Function) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_common_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Tool_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool_Function) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool_Function) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

var File_neurouter_v1_common_proto protoreflect.FileDescriptor

const file_neurouter_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x19neurouter/v1/common.proto\x12\fneurouter.v1\x1a\x1cgoogle/protobuf/struct.proto\"k\n" +
	"\x0fReasoningConfig\x125\n" +
	"\x06effort\x18\x01 \x01(\x0e2\x1d.neurouter.v1.ReasoningEffortR\x06effort\x12!\n" +
	"\ftoken_budget\x18\x02 \x01(\rR\vtokenBudget\"\x9f\x05\n" +
	"\x10GenerationConfig\x12\"\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\x03H\x02R\tmaxTokens\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\x02 \x01(\x02H\x03R\vtemperature\x88\x01\x01\x12\x18\n" +
	"\x05top_p\x18\x03 \x01(\x02H\x04R\x04topP\x88\x01\x01\x12\x18\n" +
	"\x05top_k\x18\x04 \x01(\x03H\x05R\x04topK\x88\x01\x01\x120\n" +
	"\x11frequency_penalty\x18\x05 \x01(\x02H\x06R\x10frequencyPenalty\x88\x01\x01\x12.\n" +
	"\x10presence_penalty\x18\x06 \x01(\x02H\aR\x0fpresencePenalty\x88\x01\x01\x12M\n" +
	"\x10reasoning_config\x18\a \x01(\v2\x1d.neurouter.v1.ReasoningConfigH\bR\x0freasoningConfig\x88\x01\x01\x12%\n" +
	"\x0estop_sequences\x18\b \x03(\tR\rstopSequences\x12)\n" +
	"\x0fpreset_template\x182 \x01(\tH\x00R\x0epresetTemplate\x12'\n" +
	"\x0epreset_grammar\x18< \x01(\tH\x01R\rpresetGrammar\x12#\n" +
	"\fgbnf_grammar\x18= \x01(\tH\x01R\vgbnfGrammar\x121\n" +
	"\x06schema\x18> \x01(\v2\x17.google.protobuf.StructH\x01R\x06schemaB\n" +
	"\n" +
	"\btemplateB\t\n" +
	"\agrammarB\r\n" +
	"\v_max_tokensB\x0e\n" +
	"\f_temperatureB\b\n" +
	"\x06_top_pB\b\n" +
	"\x06_top_kB\x14\n" +
	"\x12_frequency_penaltyB\x13\n" +
	"\x11_presence_penaltyB\x13\n" +
	"\x11_reasoning_config\"\xef\x01\n" +
	"\n" +
	"Statistics\x124\n" +
	"\x05usage\x18\x01 \x01(\v2\x1e.neurouter.v1.Statistics.UsageR\x05usage\x1a\xaa\x01\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\rR\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\rR\foutputTokens\x12.\n" +
	"\x13cached_input_tokens\x18\x03 \x01(\rR\x11cachedInputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\rR\x0freasoningTokens\"\xc7\x01\n" +
	"\x04Tool\x129\n" +
	"\bfunction\x18\x01 \x01(\v2\x1b.neurouter.v1.Tool.FunctionH\x00R\bfunction\x1a|\n" +
	"\bFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchemaB\x06\n" +
	"\x04tool*\xf9\x01\n" +
	"\x0fReasoningEffort\x12 \n" +
	"\x1cREASONING_EFFORT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REASONING_EFFORT_NONE\x10\x01\x12\x1c\n" +
	"\x18REASONING_EFFORT_MINIMAL\x10\x02\x12\x18\n" +
	"\x14REASONING_EFFORT_LOW\x10\x03\x12\x1b\n" +
	"\x17REASONING_EFFORT_MEDIUM\x10\x04\x12\x19\n" +
	"\x15REASONING_EFFORT_HIGH\x10\x05\x12\x1f\n" +
	"\x1bREASONING_EFFORT_EXTRA_HIGH\x10\x06\x12\x18\n" +
	"\x14REASONING_EFFORT_MAX\x10\a*s\n" +
	"\bModality\x12\x18\n" +
	"\x14MODALITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMODALITY_TEXT\x10\x01\x12\x12\n" +
	"\x0eMODALITY_IMAGE\x10\x02\x12\x12\n" +
	"\x0eMODALITY_AUDIO\x10\x03\x12\x12\n" +
	"\x0eMODALITY_VIDEO\x10\x04*\x8b\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCAPABILITY_CHAT\x10\x01\x12\x19\n" +
	"\x15CAPABILITY_COMPLETION\x10\x02\x12\x18\n" +
	"\x14CAPABILITY_EMBEDDING\x10\x03\x12\x17\n" +
	"\x13CAPABILITY_TOOL_USE\x10\x04B3Z1github.com/neuraxes/neurouter/api/neurouter/v1;v1b\x06proto3"

var (
	file_neurouter_v1_common_proto_rawDescOnce sync.Once
	file_neurouter_v1_common_proto_rawDescData []byte
)

func file_neurouter_v1_common_proto_rawDescGZIP() []byte {
	file_neurouter_v1_common_proto_rawDescOnce.Do(func() {
		file_neurouter_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neurouter_v1_common_proto_rawDesc), len(file_neurouter_v1_common_proto_rawDesc)))
	})
	return file_neurouter_v1_common_proto_rawDescData
}

var file_neurouter_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_neurouter_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_neurouter_v1_common_proto_goTypes = []any{
	(ReasoningEffort)(0),     // 0: neurouter.v1.ReasoningEffort
	(Modality)(0),            // 1: neurouter.v1.Modality
	(Capability)(0),          // 2: neurouter.v1.Capability
	(*ReasoningConfig)(nil),  // 3: neurouter.v1.ReasoningConfig
	(*GenerationConfig)(nil), // 4: neurouter.v1.GenerationConfig
	(*Statistics)(nil),       // 5: neurouter.v1.Statistics
	(*Tool)(nil),             // 6: neurouter.v1.Tool
	(*Statistics_Usage)(nil), // 7: neurouter.v1.Statistics.Usage
	(*Tool_Function)(nil),    // 8: neurouter.v1.Tool.Function
	(*structpb.Struct)(nil),  // 9: google.protobuf.Struct
}
var file_neurouter_v1_common_proto_depIdxs = []int32{
	0, // 0: neurouter.v1.ReasoningConfig.effort:type_name -> neurouter.v1.ReasoningEffort
	3, // 1: neurouter.v1.GenerationConfig.reasoning_config:type_name -> neurouter.v1.ReasoningConfig
	9, // 2: neurouter.v1.GenerationConfig.schema:type_name -> google.protobuf.Struct
	7, // 3: neurouter.v1.Statistics.usage:type_name -> neurouter.v1.Statistics.Usage
	8, // 4: neurouter.v1.Tool.function:type_name -> neurouter.v1.Tool.Function
	9, // 5: neurouter.v1.Tool.Function.input_schema:type_name -> google.protobuf.Struct
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_neurouter_v1_common_proto_init() }
func file_neurouter_v1_common_proto_init() {
	if File_neurouter_v1_common_proto != nil {
		return
	}
	file_neurouter_v1_common_proto_msgTypes[1].OneofWrappers = []any{
		(*GenerationConfig_PresetTemplate)(nil),
		(*GenerationConfig_PresetGrammar)(nil),
		(*GenerationConfig_GbnfGrammar)(nil),
		(*GenerationConfig_Schema)(nil),
	}
	file_neurouter_v1_common_proto_msgTypes[3].OneofWrappers = []any{
		(*Tool_Function_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neurouter_v1_common_proto_rawDesc), len(file_neurouter_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neurouter_v1_common_proto_goTypes,
		DependencyIndexes: file_neurouter_v1_common_proto_depIdxs,
		EnumInfos:         file_neurouter_v1_common_proto_enumTypes,
		MessageInfos:      file_neurouter_v1_common_proto_msgTypes,
	}.Build()
	File_neurouter_v1_common_proto = out.File
	file_neurouter_v1_common_proto_goTypes = nil
	file_neurouter_v1_common_proto_depIdxs = nil
}
