// Copyright 2024 Neurouter Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: neurouter/v1/completion.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the request
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The requested model to use
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// The generation configuration
	Config *GenerationConfig `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// The multi-modality content
	Contents      []*Content `protobuf:"bytes,4,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_neurouter_v1_completion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_completion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_completion_proto_rawDescGZIP(), []int{0}
}

func (x *CompleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompleteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteRequest) GetConfig() *GenerationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CompleteRequest) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

type CompleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the request
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The model used to generate the response
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// The multi-modality content
	Contents []*Content `protobuf:"bytes,3,rep,name=contents,proto3" json:"contents,omitempty"`
	// The statistics for the generation
	Statistics    *Statistics `protobuf:"bytes,4,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_neurouter_v1_completion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_completion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_completion_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompleteResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CompleteResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *CompleteResponse) GetStatistics() *Statistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

var File_neurouter_v1_completion_proto protoreflect.FileDescriptor

const file_neurouter_v1_completion_proto_rawDesc = "" +
	"\n" +
	"\x1dneurouter/v1/completion.proto\x12\fneurouter.v1\x1a\x19neurouter/v1/common.proto\x1a\x1aneurouter/v1/content.proto\"\xa2\x01\n" +
	"\x0fCompleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x126\n" +
	"\x06config\x18\x03 \x01(\v2\x1e.neurouter.v1.GenerationConfigR\x06config\x121\n" +
	"\bcontents\x18\x04 \x03(\v2\x15.neurouter.v1.ContentR\bcontents\"\xa5\x01\n" +
	"\x10CompleteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x121\n" +
	"\bcontents\x18\x03 \x03(\v2\x15.neurouter.v1.ContentR\bcontents\x128\n" +
	"\n" +
	"statistics\x18\x04 \x01(\v2\x18.neurouter.v1.StatisticsR\n" +
	"statistics2\xae\x01\n" +
	"\n" +
	"Completion\x12K\n" +
	"\bComplete\x12\x1d.neurouter.v1.CompleteRequest\x1a\x1e.neurouter.v1.CompleteResponse\"\x00\x12S\n" +
	"\x0eCompleteStream\x12\x1d.neurouter.v1.CompleteRequest\x1a\x1e.neurouter.v1.CompleteResponse\"\x000\x01B3Z1github.com/neuraxes/neurouter/api/neurouter/v1;v1b\x06proto3"

var (
	file_neurouter_v1_completion_proto_rawDescOnce sync.Once
	file_neurouter_v1_completion_proto_rawDescData []byte
)

func file_neurouter_v1_completion_proto_rawDescGZIP() []byte {
	file_neurouter_v1_completion_proto_rawDescOnce.Do(func() {
		file_neurouter_v1_completion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neurouter_v1_completion_proto_rawDesc), len(file_neurouter_v1_completion_proto_rawDesc)))
	})
	return file_neurouter_v1_completion_proto_rawDescData
}

var file_neurouter_v1_completion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_neurouter_v1_completion_proto_goTypes = []any{
	(*CompleteRequest)(nil),  // 0: neurouter.v1.CompleteRequest
	(*CompleteResponse)(nil), // 1: neurouter.v1.CompleteResponse
	(*GenerationConfig)(nil), // 2: neurouter.v1.GenerationConfig
	(*Content)(nil),          // 3: neurouter.v1.Content
	(*Statistics)(nil),       // 4: neurouter.v1.Statistics
}
var file_neurouter_v1_completion_proto_depIdxs = []int32{
	2, // 0: neurouter.v1.CompleteRequest.config:type_name -> neurouter.v1.GenerationConfig
	3, // 1: neurouter.v1.CompleteRequest.contents:type_name -> neurouter.v1.Content
	3, // 2: neurouter.v1.CompleteResponse.contents:type_name -> neurouter.v1.Content
	4, // 3: neurouter.v1.CompleteResponse.statistics:type_name -> neurouter.v1.Statistics
	0, // 4: neurouter.v1.Completion.Complete:input_type -> neurouter.v1.CompleteRequest
	0, // 5: neurouter.v1.Completion.CompleteStream:input_type -> neurouter.v1.CompleteRequest
	1, // 6: neurouter.v1.Completion.Complete:output_type -> neurouter.v1.CompleteResponse
	1, // 7: neurouter.v1.Completion.CompleteStream:output_type -> neurouter.v1.CompleteResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_neurouter_v1_completion_proto_init() }
func file_neurouter_v1_completion_proto_init() {
	if File_neurouter_v1_completion_proto != nil {
		return
	}
	file_neurouter_v1_common_proto_init()
	file_neurouter_v1_content_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neurouter_v1_completion_proto_rawDesc), len(file_neurouter_v1_completion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neurouter_v1_completion_proto_goTypes,
		DependencyIndexes: file_neurouter_v1_completion_proto_depIdxs,
		MessageInfos:      file_neurouter_v1_completion_proto_msgTypes,
	}.Build()
	File_neurouter_v1_completion_proto = out.File
	file_neurouter_v1_completion_proto_goTypes = nil
	file_neurouter_v1_completion_proto_depIdxs = nil
}
