// Copyright 2024 Neurouter Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: neurouter/v1/content.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The semantic phase of a content within a model turn.
type ContentPhase int32

const (
	// Regular content (default).
	ContentPhase_CONTENT_PHASE_NORMAL ContentPhase = 0
	// The final answer, when the upstream distinguishes it.
	ContentPhase_CONTENT_PHASE_OUTCOME ContentPhase = 1
	// Reasoning content.
	ContentPhase_CONTENT_PHASE_REASONING ContentPhase = 2
	// Reasoning summary content.
	ContentPhase_CONTENT_PHASE_REASONING_SUMMARY ContentPhase = 3
)

// Enum value maps for ContentPhase.
var (
	ContentPhase_name = map[int32]string{
		0: "CONTENT_PHASE_NORMAL",
		1: "CONTENT_PHASE_OUTCOME",
		2: "CONTENT_PHASE_REASONING",
		3: "CONTENT_PHASE_REASONING_SUMMARY",
	}
	ContentPhase_value = map[string]int32{
		"CONTENT_PHASE_NORMAL":            0,
		"CONTENT_PHASE_OUTCOME":           1,
		"CONTENT_PHASE_REASONING":         2,
		"CONTENT_PHASE_REASONING_SUMMARY": 3,
	}
)

func (x ContentPhase) Enum() *ContentPhase {
	p := new(ContentPhase)
	*p = x
	return p
}

func (x ContentPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_neurouter_v1_content_proto_enumTypes[0].Descriptor()
}

func (ContentPhase) Type() protoreflect.EnumType {
	return &file_neurouter_v1_content_proto_enumTypes[0]
}

func (x ContentPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentPhase.Descriptor instead.
func (ContentPhase) EnumDescriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{0}
}

// Represent a text content
type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_neurouter_v1_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Represent a image content
type Image struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MimeType string                 `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*Image_Url
	//	*Image_Data
	//	*Image_Base64
	Source        isImage_Source `protobuf_oneof:"source"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_neurouter_v1_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{1}
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Image) GetSource() isImage_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Image) GetUrl() string {
	if x != nil {
		if x, ok := x.Source.(*Image_Url); ok {
			return x.Url
		}
	}
	return ""
}

func (x *Image) GetData() []byte {
	if x != nil {
		if x, ok := x.Source.(*Image_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Image) GetBase64() string {
	if x != nil {
		if x, ok := x.Source.(*Image_Base64); ok {
			return x.Base64
		}
	}
	return ""
}

type isImage_Source interface {
	isImage_Source()
}

type Image_Url struct {
	// External image URL (e.g. https:// , file://)
	Url string `protobuf:"bytes,10,opt,name=url,proto3,oneof"`
}

type Image_Data struct {
	// Raw image bytes.
	Data []byte `protobuf:"bytes,11,opt,name=data,proto3,oneof"`
}

type Image_Base64 struct {
	// Base64-encoded image bytes.
	Base64 string `protobuf:"bytes,12,opt,name=base64,proto3,oneof"`
}

func (*Image_Url) isImage_Source() {}

func (*Image_Data) isImage_Source() {}

func (*Image_Base64) isImage_Source() {}

// Represent a tool use
type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inputs        []*ToolUse_Input       `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_neurouter_v1_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{2}
}

func (x *ToolUse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolUse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolUse) GetInputs() []*ToolUse_Input {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// Represent a result from tool
type ToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Outputs       []*ToolResult_Output   `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_neurouter_v1_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{3}
}

func (x *ToolResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolResult) GetOutputs() []*ToolResult_Output {
	if x != nil {
		return x.Outputs
	}
	return nil
}

// Multi-modality content
type Content struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the content
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The index of current content
	Index *uint32 `protobuf:"varint,2,opt,name=index,proto3,oneof" json:"index,omitempty"`
	// The semantic phase of the content
	Phase ContentPhase `protobuf:"varint,3,opt,name=phase,proto3,enum=neurouter.v1.ContentPhase" json:"phase,omitempty"`
	// Provider-supplied verification signature for this content.
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Content_Text
	//	*Content_Image
	//	*Content_ToolUse
	//	*Content_ToolResult
	//	*Content_Opaque
	Content       isContent_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_neurouter_v1_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{4}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *Content) GetPhase() ContentPhase {
	if x != nil {
		return x.Phase
	}
	return ContentPhase_CONTENT_PHASE_NORMAL
}

func (x *Content) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Content) GetContent() isContent_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Content) GetText() *Text {
	if x != nil {
		if x, ok := x.Content.(*Content_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *Content) GetImage() *Image {
	if x != nil {
		if x, ok := x.Content.(*Content_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *Content) GetToolUse() *ToolUse {
	if x != nil {
		if x, ok := x.Content.(*Content_ToolUse); ok {
			return x.ToolUse
		}
	}
	return nil
}

func (x *Content) GetToolResult() *ToolResult {
	if x != nil {
		if x, ok := x.Content.(*Content_ToolResult); ok {
			return x.ToolResult
		}
	}
	return nil
}

func (x *Content) GetOpaque() string {
	if x != nil {
		if x, ok := x.Content.(*Content_Opaque); ok {
			return x.Opaque
		}
	}
	return ""
}

type isContent_Content interface {
	isContent_Content()
}

type Content_Text struct {
	Text *Text `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type Content_Image struct {
	Image *Image `protobuf:"bytes,11,opt,name=image,proto3,oneof"`
}

type Content_ToolUse struct {
	ToolUse *ToolUse `protobuf:"bytes,12,opt,name=tool_use,json=toolUse,proto3,oneof"`
}

type Content_ToolResult struct {
	ToolResult *ToolResult `protobuf:"bytes,13,opt,name=tool_result,json=toolResult,proto3,oneof"`
}

type Content_Opaque struct {
	// Opaque content like encrypted CoT
	Opaque string `protobuf:"bytes,14,opt,name=opaque,proto3,oneof"`
}

func (*Content_Text) isContent_Content() {}

func (*Content_Image) isContent_Content() {}

func (*Content_ToolUse) isContent_Content() {}

func (*Content_ToolResult) isContent_Content() {}

func (*Content_Opaque) isContent_Content() {}

type ToolUse_Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index *uint32                `protobuf:"varint,1,opt,name=index,proto3,oneof" json:"index,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*ToolUse_Input_Text
	Input         isToolUse_Input_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse_Input) Reset() {
	*x = ToolUse_Input{}
	mi := &file_neurouter_v1_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse_Input) ProtoMessage() {}

func (x *ToolUse_Input) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse_Input.ProtoReflect.Descriptor instead.
func (*ToolUse_Input) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ToolUse_Input) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ToolUse_Input) GetInput() isToolUse_Input_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ToolUse_Input) GetText() string {
	if x != nil {
		if x, ok := x.Input.(*ToolUse_Input_Text); ok {
			return x.Text
		}
	}
	return ""
}

type isToolUse_Input_Input interface {
	isToolUse_Input_Input()
}

type ToolUse_Input_Text struct {
	Text string `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

func (*ToolUse_Input_Text) isToolUse_Input_Input() {}

type ToolResult_Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index *uint32                `protobuf:"varint,1,opt,name=index,proto3,oneof" json:"index,omitempty"`
	// Types that are valid to be assigned to Output:
	//
	//	*ToolResult_Output_Text
	//	*ToolResult_Output_Image
	Output        isToolResult_Output_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult_Output) Reset() {
	*x = ToolResult_Output{}
	mi := &file_neurouter_v1_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult_Output) ProtoMessage() {}

func (x *ToolResult_Output) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult_Output.ProtoReflect.Descriptor instead.
func (*ToolResult_Output) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_content_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ToolResult_Output) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ToolResult_Output) GetOutput() isToolResult_Output_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ToolResult_Output) GetText() string {
	if x != nil {
		if x, ok := x.Output.(*ToolResult_Output_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ToolResult_Output) GetImage() *Image {
	if x != nil {
		if x, ok := x.Output.(*ToolResult_Output_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isToolResult_Output_Output interface {
	isToolResult_Output_Output()
}

type ToolResult_Output_Text struct {
	Text string `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type ToolResult_Output_Image struct {
	Image *Image `protobuf:"bytes,11,opt,name=image,proto3,oneof"`
}

func (*ToolResult_Output_Text) isToolResult_Output_Output() {}

func (*ToolResult_Output_Image) isToolResult_Output_Output() {}

var File_neurouter_v1_content_proto protoreflect.FileDescriptor

const file_neurouter_v1_content_proto_rawDesc = "" +
	"\n" +
	"\x1aneurouter/v1/content.proto\x12\fneurouter.v1\"\x1a\n" +
	"\x04Text\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"r\n" +
	"\x05Image\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x12\n" +
	"\x03url\x18\n" +
	" \x01(\tH\x00R\x03url\x12\x14\n" +
	"\x04data\x18\v \x01(\fH\x00R\x04data\x12\x18\n" +
	"\x06base64\x18\f \x01(\tH\x00R\x06base64B\b\n" +
	"\x06source\"\xaf\x01\n" +
	"\aToolUse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x06inputs\x18\x03 \x03(\v2\x1b.neurouter.v1.ToolUse.InputR\x06inputs\x1aK\n" +
	"\x05Input\x12\x19\n" +
	"\x05index\x18\x01 \x01(\rH\x01R\x05index\x88\x01\x01\x12\x14\n" +
	"\x04text\x18\n" +
	" \x01(\tH\x00R\x04textB\a\n" +
	"\x05inputB\b\n" +
	"\x06_index\"\xd3\x01\n" +
	"\n" +
	"ToolResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\aoutputs\x18\x02 \x03(\v2\x1f.neurouter.v1.ToolResult.OutputR\aoutputs\x1az\n" +
	"\x06Output\x12\x19\n" +
	"\x05index\x18\x01 \x01(\rH\x01R\x05index\x88\x01\x01\x12\x14\n" +
	"\x04text\x18\n" +
	" \x01(\tH\x00R\x04text\x12+\n" +
	"\x05image\x18\v \x01(\v2\x13.neurouter.v1.ImageH\x00R\x05imageB\b\n" +
	"\x06outputB\b\n" +
	"\x06_index\"\xfb\x02\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05index\x18\x02 \x01(\rH\x01R\x05index\x88\x01\x01\x120\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x1a.neurouter.v1.ContentPhaseR\x05phase\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\x12(\n" +
	"\x04text\x18\n" +
	" \x01(\v2\x12.neurouter.v1.TextH\x00R\x04text\x12+\n" +
	"\x05image\x18\v \x01(\v2\x13.neurouter.v1.ImageH\x00R\x05image\x122\n" +
	"\btool_use\x18\f \x01(\v2\x15.neurouter.v1.ToolUseH\x00R\atoolUse\x12;\n" +
	"\vtool_result\x18\r \x01(\v2\x18.neurouter.v1.ToolResultH\x00R\n" +
	"toolResult\x12\x18\n" +
	"\x06opaque\x18\x0e \x01(\tH\x00R\x06opaqueB\t\n" +
	"\acontentB\b\n" +
	"\x06_index*\x85\x01\n" +
	"\fContentPhase\x12\x18\n" +
	"\x14CONTENT_PHASE_NORMAL\x10\x00\x12\x19\n" +
	"\x15CONTENT_PHASE_OUTCOME\x10\x01\x12\x1b\n" +
	"\x17CONTENT_PHASE_REASONING\x10\x02\x12#\n" +
	"\x1fCONTENT_PHASE_REASONING_SUMMARY\x10\x03B3Z1github.com/neuraxes/neurouter/api/neurouter/v1;v1b\x06proto3"

var (
	file_neurouter_v1_content_proto_rawDescOnce sync.Once
	file_neurouter_v1_content_proto_rawDescData []byte
)

func file_neurouter_v1_content_proto_rawDescGZIP() []byte {
	file_neurouter_v1_content_proto_rawDescOnce.Do(func() {
		file_neurouter_v1_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neurouter_v1_content_proto_rawDesc), len(file_neurouter_v1_content_proto_rawDesc)))
	})
	return file_neurouter_v1_content_proto_rawDescData
}

var file_neurouter_v1_content_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neurouter_v1_content_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_neurouter_v1_content_proto_goTypes = []any{
	(ContentPhase)(0),         // 0: neurouter.v1.ContentPhase
	(*Text)(nil),              // 1: neurouter.v1.Text
	(*Image)(nil),             // 2: neurouter.v1.Image
	(*ToolUse)(nil),           // 3: neurouter.v1.ToolUse
	(*ToolResult)(nil),        // 4: neurouter.v1.ToolResult
	(*Content)(nil),           // 5: neurouter.v1.Content
	(*ToolUse_Input)(nil),     // 6: neurouter.v1.ToolUse.Input
	(*ToolResult_Output)(nil), // 7: neurouter.v1.ToolResult.Output
}
var file_neurouter_v1_content_proto_depIdxs = []int32{
	6, // 0: neurouter.v1.ToolUse.inputs:type_name -> neurouter.v1.ToolUse.Input
	7, // 1: neurouter.v1.ToolResult.outputs:type_name -> neurouter.v1.ToolResult.Output
	0, // 2: neurouter.v1.Content.phase:type_name -> neurouter.v1.ContentPhase
	1, // 3: neurouter.v1.Content.text:type_name -> neurouter.v1.Text
	2, // 4: neurouter.v1.Content.image:type_name -> neurouter.v1.Image
	3, // 5: neurouter.v1.Content.tool_use:type_name -> neurouter.v1.ToolUse
	4, // 6: neurouter.v1.Content.tool_result:type_name -> neurouter.v1.ToolResult
	2, // 7: neurouter.v1.ToolResult.Output.image:type_name -> neurouter.v1.Image
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_neurouter_v1_content_proto_init() }
func file_neurouter_v1_content_proto_init() {
	if File_neurouter_v1_content_proto != nil {
		return
	}
	file_neurouter_v1_content_proto_msgTypes[1].OneofWrappers = []any{
		(*Image_Url)(nil),
		(*Image_Data)(nil),
		(*Image_Base64)(nil),
	}
	file_neurouter_v1_content_proto_msgTypes[4].OneofWrappers = []any{
		(*Content_Text)(nil),
		(*Content_Image)(nil),
		(*Content_ToolUse)(nil),
		(*Content_ToolResult)(nil),
		(*Content_Opaque)(nil),
	}
	file_neurouter_v1_content_proto_msgTypes[5].OneofWrappers = []any{
		(*ToolUse_Input_Text)(nil),
	}
	file_neurouter_v1_content_proto_msgTypes[6].OneofWrappers = []any{
		(*ToolResult_Output_Text)(nil),
		(*ToolResult_Output_Image)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neurouter_v1_content_proto_rawDesc), len(file_neurouter_v1_content_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neurouter_v1_content_proto_goTypes,
		DependencyIndexes: file_neurouter_v1_content_proto_depIdxs,
		EnumInfos:         file_neurouter_v1_content_proto_enumTypes,
		MessageInfos:      file_neurouter_v1_content_proto_msgTypes,
	}.Build()
	File_neurouter_v1_content_proto = out.File
	file_neurouter_v1_content_proto_goTypes = nil
	file_neurouter_v1_content_proto_depIdxs = nil
}
