// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: neurouter/v1/embedding.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationEmbeddingEmbed = "/neurouter.v1.Embedding/Embed"

type EmbeddingHTTPServer interface {
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
}

func RegisterEmbeddingHTTPServer(s *http.Server, srv EmbeddingHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/embed", _Embedding_Embed0_HTTP_Handler(srv))
}

func _Embedding_Embed0_HTTP_Handler(srv EmbeddingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmbedRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationEmbeddingEmbed)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Embed(ctx, req.(*EmbedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmbedResponse)
		return ctx.Result(200, reply)
	}
}

type EmbeddingHTTPClient interface {
	Embed(ctx context.Context, req *EmbedRequest, opts ...http.CallOption) (rsp *EmbedResponse, err error)
}

type EmbeddingHTTPClientImpl struct {
	cc *http.Client
}

func NewEmbeddingHTTPClient(client *http.Client) EmbeddingHTTPClient {
	return &EmbeddingHTTPClientImpl{client}
}

func (c *EmbeddingHTTPClientImpl) Embed(ctx context.Context, in *EmbedRequest, opts ...http.CallOption) (*EmbedResponse, error) {
	var out EmbedResponse
	pattern := "/v1/embed"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationEmbeddingEmbed),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
