// Copyright 2024 Neurouter Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: neurouter/v1/embedding.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contents []*Content `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
}

func (x *EmbedReq) Reset() {
	*x = EmbedReq{}
	mi := &file_neurouter_v1_embedding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedReq) ProtoMessage() {}

func (x *EmbedReq) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_embedding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedReq.ProtoReflect.Descriptor instead.
func (*EmbedReq) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_embedding_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedReq) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

type EmbedResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Embedding []float32 `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
}

func (x *EmbedResp) Reset() {
	*x = EmbedResp{}
	mi := &file_neurouter_v1_embedding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResp) ProtoMessage() {}

func (x *EmbedResp) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_embedding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResp.ProtoReflect.Descriptor instead.
func (*EmbedResp) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_embedding_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResp) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

var File_neurouter_v1_embedding_proto protoreflect.FileDescriptor

var file_neurouter_v1_embedding_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x65,
	0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x6e, 0x65, 0x75, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6e, 0x65, 0x75, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x08, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x31, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x29, 0x0a, 0x09, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x32,
	0x5b, 0x0a, 0x09, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x4e, 0x0a, 0x05,
	0x45, 0x6d, 0x62, 0x65, 0x64, 0x12, 0x16, 0x2e, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x6e, 0x65, 0x75, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x62,
	0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a, 0x01,
	0x2a, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x65, 0x75, 0x72, 0x61,
	0x78, 0x65, 0x73, 0x2f, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6e, 0x65, 0x75, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_neurouter_v1_embedding_proto_rawDescOnce sync.Once
	file_neurouter_v1_embedding_proto_rawDescData = file_neurouter_v1_embedding_proto_rawDesc
)

func file_neurouter_v1_embedding_proto_rawDescGZIP() []byte {
	file_neurouter_v1_embedding_proto_rawDescOnce.Do(func() {
		file_neurouter_v1_embedding_proto_rawDescData = protoimpl.X.CompressGZIP(file_neurouter_v1_embedding_proto_rawDescData)
	})
	return file_neurouter_v1_embedding_proto_rawDescData
}

var file_neurouter_v1_embedding_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_neurouter_v1_embedding_proto_goTypes = []any{
	(*EmbedReq)(nil),  // 0: neurouter.v1.EmbedReq
	(*EmbedResp)(nil), // 1: neurouter.v1.EmbedResp
	(*Content)(nil),   // 2: neurouter.v1.Content
}
var file_neurouter_v1_embedding_proto_depIdxs = []int32{
	2, // 0: neurouter.v1.EmbedReq.contents:type_name -> neurouter.v1.Content
	0, // 1: neurouter.v1.Embedding.Embed:input_type -> neurouter.v1.EmbedReq
	1, // 2: neurouter.v1.Embedding.Embed:output_type -> neurouter.v1.EmbedResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_neurouter_v1_embedding_proto_init() }
func file_neurouter_v1_embedding_proto_init() {
	if File_neurouter_v1_embedding_proto != nil {
		return
	}
	file_neurouter_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neurouter_v1_embedding_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neurouter_v1_embedding_proto_goTypes,
		DependencyIndexes: file_neurouter_v1_embedding_proto_depIdxs,
		MessageInfos:      file_neurouter_v1_embedding_proto_msgTypes,
	}.Build()
	File_neurouter_v1_embedding_proto = out.File
	file_neurouter_v1_embedding_proto_rawDesc = nil
	file_neurouter_v1_embedding_proto_goTypes = nil
	file_neurouter_v1_embedding_proto_depIdxs = nil
}
