// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsNoUpstream(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NO_UPSTREAM.String() && e.Code == 500
}

func ErrorNoUpstream(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_NO_UPSTREAM.String(), fmt.Sprintf(format, args...))
}
