// Copyright 2024 Neurouter Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: neurouter/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_NO_UPSTREAM ErrorReason = 0
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "NO_UPSTREAM",
	}
	ErrorReason_value = map[string]int32{
		"NO_UPSTREAM": 0,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_neurouter_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_neurouter_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_neurouter_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_neurouter_v1_error_reason_proto protoreflect.FileDescriptor

const file_neurouter_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1fneurouter/v1/error_reason.proto\x12\fneurouter.v1\x1a\x13errors/errors.proto*$\n" +
	"\vErrorReason\x12\x0f\n" +
	"\vNO_UPSTREAM\x10\x00\x1a\x04\xa0E\xf4\x03B3Z1github.com/neuraxes/neurouter/api/neurouter/v1;v1b\x06proto3"

var (
	file_neurouter_v1_error_reason_proto_rawDescOnce sync.Once
	file_neurouter_v1_error_reason_proto_rawDescData []byte
)

func file_neurouter_v1_error_reason_proto_rawDescGZIP() []byte {
	file_neurouter_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_neurouter_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neurouter_v1_error_reason_proto_rawDesc), len(file_neurouter_v1_error_reason_proto_rawDesc)))
	})
	return file_neurouter_v1_error_reason_proto_rawDescData
}

var file_neurouter_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neurouter_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: neurouter.v1.ErrorReason
}
var file_neurouter_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_neurouter_v1_error_reason_proto_init() }
func file_neurouter_v1_error_reason_proto_init() {
	if File_neurouter_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neurouter_v1_error_reason_proto_rawDesc), len(file_neurouter_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neurouter_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_neurouter_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_neurouter_v1_error_reason_proto_enumTypes,
	}.Build()
	File_neurouter_v1_error_reason_proto = out.File
	file_neurouter_v1_error_reason_proto_goTypes = nil
	file_neurouter_v1_error_reason_proto_depIdxs = nil
}
