// Copyright 2024 Neurouter Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: neurouter/v1/model.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModelSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the model.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The display name of the model.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The entity that owns the model.
	From string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	// The model service provider.
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// The modalities supported by the model.
	Modalities []Modality `protobuf:"varint,5,rep,packed,name=modalities,proto3,enum=neurouter.v1.Modality" json:"modalities,omitempty"`
	// The capabilities of the model.
	Capabilities  []Capability `protobuf:"varint,6,rep,packed,name=capabilities,proto3,enum=neurouter.v1.Capability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelSpec) Reset() {
	*x = ModelSpec{}
	mi := &file_neurouter_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSpec) ProtoMessage() {}

func (x *ModelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSpec.ProtoReflect.Descriptor instead.
func (*ModelSpec) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *ModelSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelSpec) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ModelSpec) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelSpec) GetModalities() []Modality {
	if x != nil {
		return x.Modalities
	}
	return nil
}

func (x *ModelSpec) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ListModelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelReq) Reset() {
	*x = ListModelReq{}
	mi := &file_neurouter_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelReq) ProtoMessage() {}

func (x *ListModelReq) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelReq.ProtoReflect.Descriptor instead.
func (*ListModelReq) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_model_proto_rawDescGZIP(), []int{1}
}

type ListModelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelSpec           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelResp) Reset() {
	*x = ListModelResp{}
	mi := &file_neurouter_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelResp) ProtoMessage() {}

func (x *ListModelResp) ProtoReflect() protoreflect.Message {
	mi := &file_neurouter_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelResp.ProtoReflect.Descriptor instead.
func (*ListModelResp) Descriptor() ([]byte, []int) {
	return file_neurouter_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelResp) GetModels() []*ModelSpec {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_neurouter_v1_model_proto protoreflect.FileDescriptor

const file_neurouter_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x18neurouter/v1/model.proto\x12\fneurouter.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x19neurouter/v1/common.proto\"\xd5\x01\n" +
	"\tModelSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x126\n" +
	"\n" +
	"modalities\x18\x05 \x03(\x0e2\x16.neurouter.v1.ModalityR\n" +
	"modalities\x12<\n" +
	"\fcapabilities\x18\x06 \x03(\x0e2\x18.neurouter.v1.CapabilityR\fcapabilities\"\x0e\n" +
	"\fListModelReq\"@\n" +
	"\rListModelResp\x12/\n" +
	"\x06models\x18\x01 \x03(\v2\x17.neurouter.v1.ModelSpecR\x06models2a\n" +
	"\x05Model\x12X\n" +
	"\tListModel\x12\x1a.neurouter.v1.ListModelReq\x1a\x1b.neurouter.v1.ListModelResp\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/modelsB3Z1github.com/neuraxes/neurouter/api/neurouter/v1;v1b\x06proto3"

var (
	file_neurouter_v1_model_proto_rawDescOnce sync.Once
	file_neurouter_v1_model_proto_rawDescData []byte
)

func file_neurouter_v1_model_proto_rawDescGZIP() []byte {
	file_neurouter_v1_model_proto_rawDescOnce.Do(func() {
		file_neurouter_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neurouter_v1_model_proto_rawDesc), len(file_neurouter_v1_model_proto_rawDesc)))
	})
	return file_neurouter_v1_model_proto_rawDescData
}

var file_neurouter_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_neurouter_v1_model_proto_goTypes = []any{
	(*ModelSpec)(nil),     // 0: neurouter.v1.ModelSpec
	(*ListModelReq)(nil),  // 1: neurouter.v1.ListModelReq
	(*ListModelResp)(nil), // 2: neurouter.v1.ListModelResp
	(Modality)(0),         // 3: neurouter.v1.Modality
	(Capability)(0),       // 4: neurouter.v1.Capability
}
var file_neurouter_v1_model_proto_depIdxs = []int32{
	3, // 0: neurouter.v1.ModelSpec.modalities:type_name -> neurouter.v1.Modality
	4, // 1: neurouter.v1.ModelSpec.capabilities:type_name -> neurouter.v1.Capability
	0, // 2: neurouter.v1.ListModelResp.models:type_name -> neurouter.v1.ModelSpec
	1, // 3: neurouter.v1.Model.ListModel:input_type -> neurouter.v1.ListModelReq
	2, // 4: neurouter.v1.Model.ListModel:output_type -> neurouter.v1.ListModelResp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_neurouter_v1_model_proto_init() }
func file_neurouter_v1_model_proto_init() {
	if File_neurouter_v1_model_proto != nil {
		return
	}
	file_neurouter_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neurouter_v1_model_proto_rawDesc), len(file_neurouter_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neurouter_v1_model_proto_goTypes,
		DependencyIndexes: file_neurouter_v1_model_proto_depIdxs,
		MessageInfos:      file_neurouter_v1_model_proto_msgTypes,
	}.Build()
	File_neurouter_v1_model_proto = out.File
	file_neurouter_v1_model_proto_goTypes = nil
	file_neurouter_v1_model_proto_depIdxs = nil
}
